- name: Gather facts
  hosts: all
  tasks: []

- name: Deploy pihole
  hosts: pihole
  become: true
  serial: 1
  roles:
    - keepalived-pihole
    - pihole
    - sync

- name: Deploy caddy
  hosts: caddy
  serial: 1
  become: true
  roles:
    - keepalived-caddy
    - caddy

- name: Deploy homebridge
  hosts: homebridge
  serial: 1
  become: true
  roles:
    - homebridge
