- name: Populate service facts
  service_facts:

- name: Ensure keepalived service is started
  service:
    name: keepalived
    state: started
  register: result
  when: "'keepalived' in services"
  failed_when:
    - result.failed == true
    - '"Could not find the requested service" not in result.msg'
